pipeline {
					
					agent any
					
					tools {
						maven "Maven 3.9.9"
					}
					stages {
						stage('Stage 1 - Checkout Code') {
							steps {
								//Get the code form GITHUB							
                                git 'https://github.com/shubham182005/exp7'
							}
						}
						stage('Stage 2 - Compile Code') {
							steps {
								//cmd to compile the code							
                                bat "mvn compile"
							}
						}
						stage('Stage 3 - Run Unit Tests') {
							steps {
								//cmd to run tests							
                                bat "mvn test"
							}
						}
						stage('Stage 4 -Create build') {
							steps {
								//cmd to create the build of project							
                                bat "mvn testpackage"
							}
						}
	
					}
					post{
					    	failure {
					
					        echo " build failed"
				         }
					}
				
					
				}
